### ISSUE TITLE
两个问题

### ISSUE THREAD

**Issue by jiaojin** [dnlcrl/deep-residual-networks-pyfunt#1]
问题1：pip list中有pyfunt，运行requirements.txt找不到，在python包中也找不到，是安装失败了吗。而且用sudo pip install git+git://github.com/dnlcrl/PyFunt.git安装会报错。SSLError: The read operation timed out
Storing debug log for failure in /home/zxc/.pip/pip.log

问题2：运行train.py时，No module named pydatset.cifar10，但是在/usr/local/lib/python2.7/dist-packages路径下，确实已经安装了pydatset。

**Comment by dnlcrl** [comment]
Hi jiaojin,

please keep in mind that this is an unmaintained repository, anyway I just tried reinstalling the needed packages with `pip install -r requirements.txt`, and it worked correctly. 

For the "The read operation timed out" error you can refer to [this](http://stackoverflow.com/questions/18958508/sslerror-the-read-operation-timed-out-when-using-pip), [this](https://github.com/boto/boto3/issues/185), or [this](https://github.com/Mikadily/poloniexlendingbot/issues/151), or any other similar page, as it should not be caused by this package.

For the second error, you should be able to solve it by correctly installing [PyDatSet](https://github.com/dnlcrl/pydatset). 

Please next time use the english language so I don't have to translate your message in order to understand what the problem is.
