### ISSUE TITLE
ImportError: cannot import name ResNet

### ISSUE THREAD

**Issue by jiaojin** [dnlcrl/deep-residual-networks-pyfunt#2]
Thank you very much for your answer！
ImportError: cannot import name ResNet
I have encountered this problem，what should I do next?

**Comment by dnlcrl** [comment]
I edited the train.py file, it should work now (replaced ResNet with resnet). Please keep in mind that this is an unmaintained repo, if you find other similar errors you can simply fix them and make a pull request. 

Also I strongly suggest you to use instead a deep learning package as tensorflow or pyTorch or one of the many others available, because this repo along with pyfunt and pydatset are for demonstration only.

If you want to train a residual network as in http://arxiv.org/abs/1512.03385, I suggest you to check this repo (where lua + torch are used): https://github.com/gcr/torch-residual-networks.
